spring.application.name=inpost_assessment

spring.datasource.url=jdbc:postgresql://localhost:5432/inpostdb
spring.datasource.username=springuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true